title: Elankovan Munuswamy Gopal
description: Masters Research Scholar, Indian Institute of Technology Madras
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
# analytics_id: [Your Google Analytics tracking ID]theme: jekyll-theme-cayman
email: elankovanmg@gmail.com

# markdown: kramdown

theme: jekyll-theme-cayman
